"""add more field

Revision ID: 365ccf3aacfc
Revises: 028fb4441699
Create Date: 2018-01-18 14:27:48.869921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365ccf3aacfc'
down_revision = '028fb4441699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_data', sa.Column('relative_humidity', sa.String(length=32), nullable=True))
    op.add_column('device_data', sa.Column('temperature', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_data', 'temperature')
    op.drop_column('device_data', 'relative_humidity')
    # ### end Alembic commands ###
